Write a program to create a function show_employee() using the following conditions.
It should accept the employeeâ€™s name and salary and display both.
If the salary is missing in the function call then assign default value 9000 to salary

In [ ]:
def show_Employee(name,salary=9000):
   print(f"name:{name}salary:{salary}")
   show_Employee("Ben",12000)
   show_Employee("Jessa")

name:Ben salary:12000
name:Jessa salary:9000

Create an outer function that will accept two parameters, a and b.
Create an inner function inside an outer function that will calculate the addition of a and b
At last, an outer function will add 5 into addition and return it

In [ ]:
def outer_function(a,b):
 def inner_function(x,y):
    return x+y
    addition=inner_function(a,b)
    final_result=addition+5
    return final_result
    result=outer_function(2,2)
    print("final result=",result)

final result=9

Generate a Python list of all the even numbers between 4 to 30

In [ ]:
num=0
def even():
  for num in range(4,31):
    if(num%2==0):
      num=list[num]
      print(num)
even()

list[4]
list[6]
list[8]
list[10]
list[12]
list[14]
list[16]
list[18]
list[20]
list[22]
list[24]
list[26]
list[28]
list[30]

Given a list, the task is to write a Python program to check if the value exists in the list or not using the lambda function.

In [ ]:
def findnumber(n,v):
  result=list(filter(lambda x:x==v,n))
  print("input:",n)
  print("element:",v)
  if result:
    print("value found in the list.")
  else:
    print("value not foundin the list")
    n=[1,2,3,4,5]
    v=3
    findnumber(n,v)
    n=[1,2,3,4,5]
    v=7
    findnumber(n,v)

input:[1,2,3,4,5]
element:3
value found inthe list.
input:[1,2,3,4,5]
element:7
value not found in the list.

Sort the points based on their sum of elements in the tuples

points = [(1, 2), (5, 3), (0, 7), (3, 1)]

In [ ]:
t=[(1,2),(5,3),(0,7),(3,1),]
print("input:",t)
t.sort(key=lambda x:x[0]+x[1])
print("output",t)

input: [(1, 2), (5, 3), (0, 7), (3, 1)]
output [(1, 2), (3, 1), (0, 7), (5, 3)]

6.Write a python function, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number. Return the results as a list

In [ ]:
def result():
  result= []
  for num in range(1000,3001):
    digits = [int(digit) for digit in str(num)]
  if all(digit % 2 == 0 for digit in digits):
    result.append(num)
  print (result)

In [ ]:
result()

[]

[2000,2002,2004,2006,2008,2020,2022,2024,2025,2026,2027,2028]

7.Write a python function that accepts a sentence and calculate and return the number of letters and digits.
Suppose the following input is supplied to the program:
hello world! 123
Then, the output should be:
LETTERS 10
DIGITS 3

In [ ]:
def fun(x):
  letters=0
  digits=0
  for i in x:
    if i.isalpha():
       letters+=1
    elif i. isdigit():
      digits+=1
  return letters,digits
  a="farsa@123"
  letters,digits=fun(a)
  print("LETTERS", letters)
  print("DIGITS" , digits)

letters 4
digits3

8.Write a Python program to convert all the characters into uppercase and lowercase and eliminate duplicate letters from a given sequence. Use the map() function

In [ ]:
def upper_lower(seq):
   return seq.upper(),seq.lower()
   #sequence=input("enter the sequence :")
   sequence=['f','k','t','j','J','E','t']
   x=set(map(upper_lower,sequence))
   print(x)

{('T, 't'), ('k','k'), ('J','j'), ('E','e'), ('F', 'f')}

9.Write a Python program to element wise add two given lists and find the difference between them. Use the map() function

In [ ]:
l1=[4,8,3,5,6,8]
l2=[3,1,4,1,2]
print('adding the elememnts:\n',list(map(lambda x,y:x+y,l1,l2)))
print('subtracting the elements:|n',list(map(lambda x,y:x-y,l1,l2)))

adding the elememnts:
 [7, 9, 7, 6, 8]
subtracting the elements:|n [1, 7, -1, 4, 4]

10.Write a Python program to filter the height and weight of students, which are stored in a dictionary using lambda.
Original Dictionary:

In [ ]:
my_dic={'Cierra Vega': (6.2, 71), 'Alden Cantrell': (5.9, 65), 'Kierra Gentry': (6.0, 68), 'Pierre Cox': (5.8, 66)}

f=dict(filter(lambda x:(x[1][0],x[1][1])>(6.0,70) ,my_dic.items()))
f

{'Cierra Vega': (6.2, 71)}

11.Write a Python program to remove all elements from a given list present in another list using lambda.

In [ ]:
list1= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

list2= [2, 4, 6, 8]

sorted_filter = list(filter(lambda x : x not in list2, list1))
print(sorted_filter)

[1, 3, 5, 7, 9, 10]

12.Write a Python program to calculate the product of a given list of numbers using lambda.

In [1]:
import functools
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
result = functools.reduce(lambda x,y : x*y,list1)
print(result)

3628800

13. Write a Python program to multiply all the numbers in a given list using lambda.

In [2]:
import functools
list1 = [4, 3, 2, 2, -1, 18]
result = functools.reduce(lambda x,y : x*y,list1)
print(result)

-864

14.Write a Python program to calculate the average value of the numbers in a given tuple of tuples using lambda.

In [3]:
original_tuple = ((10, 10, 10), (30, 45, 56), (81, 80, 39), (1, 2, 3))

average_tuple = tuple(map(lambda *args : sum(args)/len(args), *original_tuple))

print(average_tuple)

(30.5, 34.25, 27.0)

15.Write a Python program to sort a given mixed list of integers and strings using lambda. Numbers must be sorted before strings.

In [4]:
list1=[19, 'red', 12, 'green', 'blue', 10, 'white', 'green', 1]
list1.sort(key=lambda x:(isinstance(x,str),x))
print(list1)

[1, 10, 12, 19, 'blue', 'green', 'green', 'red', 'white']

16.Write a Python program to count the occurrences of items in a given list using lambda.

In [5]:
original_list = [3, 4, 5, 8, 0, 3, 8, 5, 0, 3, 1, 5, 2, 3, 4, 2]

occurrence_list = dict(map(lambda x : (x, original_list.count(x)),original_list))

print(occurrence_list)

{3: 4, 4: 2, 5: 3, 8: 2, 0: 2, 1: 1, 2: 2}

 17.Write a Python program to remove None values from a given list using the lambda function.

In [6]:
original_list = [12, 0, None, 23, None, -55, 234, 89, None, 0, 6, -12]

filtered_list = list(filter((lambda x: x is not None),original_list))

print(filtered_list)

[12, 0, 23, -55, 234, 89, 0, 6, -12]